#!/usr/bin/env bash
# AI Content Planner — Generate content ideas LLMs will cite
# Usage: ./content-planner.sh <niche> [output-file]
# Generates question-based content plan targeting AI citation

set -uo pipefail

NICHE="${1:-}"
OUTPUT="${2:-workspace/artifacts/geo-content-plan.md}"

if [ -z "$NICHE" ]; then
  echo "Usage: $0 <niche> [output-file]"
  echo "Example: $0 'AI agent tools' plan.md"
  exit 1
fi

mkdir -p "$(dirname "$OUTPUT")"

cat > "$OUTPUT" << 'TEMPLATE'
# AI Content Plan: NICHE_PLACEHOLDER

Generated: DATE_PLACEHOLDER

## How LLMs Choose What to Cite

LLMs cite content that:
1. **Directly answers a question** — "How do I X?" → your article explains X
2. **Provides unique data** — original research, benchmarks, case studies
3. **Is structured clearly** — H2/H3 headings that match question phrasing
4. **Is referenced elsewhere** — backlinks from forums, Reddit, HN, other blogs

## Content Types by Citation Potential

### 🔴 Highest Citation (write these first)

**"How to" guides** — step-by-step instructions
LLMs love these because they directly answer user questions.

| # | Title | Target Query | Type |
|---|-------|-------------|------|
| 1 | | "how to [action] with [tool]" | Tutorial |
| 2 | | "how to set up [thing]" | Setup guide |
| 3 | | "[tool] getting started guide" | Onboarding |

**Research/data posts** — original findings
These get cited because no one else has this data.

| # | Title | Target Query | Type |
|---|-------|-------------|------|
| 4 | | "[topic] statistics 2026" | Research |
| 5 | | "[topic] benchmark comparison" | Comparison |
| 6 | | "is [thing] safe/reliable" | Trust piece |

### 🟡 Medium Citation

**Comparison posts** — X vs Y
Users ask LLMs to compare things constantly.

| # | Title | Target Query | Type |
|---|-------|-------------|------|
| 7 | | "[thing A] vs [thing B]" | Comparison |
| 8 | | "best [category] tools 2026" | Listicle |

**Explainer posts** — what is X
Foundational content that gets cited for definitions.

| # | Title | Target Query | Type |
|---|-------|-------------|------|
| 9 | | "what is [concept]" | Explainer |
| 10 | | "[concept] explained simply" | Beginner guide |

### 🟢 Lower Citation (but builds authority)

**Opinion/analysis** — why X matters
Less directly cited but builds topical authority.

| # | Title | Target Query | Type |
|---|-------|-------------|------|
| 11 | | "why [trend] matters" | Analysis |
| 12 | | "[topic] predictions 2026" | Thought leadership |

## Content Structure Template

Every article should follow this structure for maximum AI citation:

```markdown
# [Title that matches a question]

[Opening paragraph that directly answers the question in 2-3 sentences]

## TL;DR
[Bullet point summary — LLMs often extract this]

## [H2 sections that are themselves questions or clear topics]

### [H3 subsections for detail]

## FAQ
[3-5 related questions with concise answers]
[These are gold for LLM citation — each FAQ item can be cited independently]
```

## Optimization Checklist Per Article

- [ ] Title matches a natural language question
- [ ] First paragraph answers the question directly (no preamble)
- [ ] TL;DR section near the top
- [ ] H2/H3 headings are descriptive (not clever/cute)
- [ ] Includes at least 1 original data point, stat, or finding
- [ ] FAQ section with 3-5 related questions
- [ ] Meta description summarizes the answer (80-160 chars)
- [ ] JSON-LD Article schema markup
- [ ] Internal links to related content
- [ ] External links to authoritative sources

## Publishing & Distribution

After publishing each article:
1. Share on X with a hook that invites discussion
2. Post to relevant subreddits (r/artificial, r/SideProject, etc.)
3. Submit to HN if it contains original research
4. Update sitemap.xml
5. Update llms.txt with new page reference
6. Wait 2 weeks, then check Perplexity/ChatGPT for citation

## Monthly Review

- [ ] Check Perplexity: search your key queries, see if you're cited
- [ ] Check ChatGPT: ask it about your topic, see if it mentions you
- [ ] Update existing articles with new data/findings
- [ ] Add new FAQ items based on actual user questions
- [ ] Review analytics for most-visited pages → double down on those topics

---
Generated by AI Visibility Pro — Content Planner
TEMPLATE

# Replace placeholders
sed -i "s|NICHE_PLACEHOLDER|$NICHE|g" "$OUTPUT"
sed -i "s|DATE_PLACEHOLDER|$(date +%Y-%m-%d)|g" "$OUTPUT"

echo "✅ Content plan saved: $OUTPUT"
echo "Fill in the table rows with titles specific to: $NICHE"
echo "Prioritize 🔴 Highest Citation articles first"
