#!/usr/bin/env bash
# SWOT Analysis Generator
# Creates a structured SWOT template for a business/product/idea
# Usage: ./swot-generator.sh <business-name> [output-file]

set -uo pipefail

BUSINESS="${1:?Usage: swot-generator.sh <business-name> [output-file]}"
OUTPUT="${2:-workspace/artifacts/swot-${BUSINESS// /-}.md}"
mkdir -p "$(dirname "$OUTPUT")"

cat > "$OUTPUT" << TEMPLATE
# SWOT Analysis: $BUSINESS
**Date:** $(date +%Y-%m-%d)

---

## Strengths (Internal — what we do well)

| # | Strength | Evidence | Leverage How? |
|---|----------|----------|---------------|
| 1 | | | |
| 2 | | | |
| 3 | | | |
| 4 | | | |
| 5 | | | |

**Key question:** What do customers/users say we're best at?

---

## Weaknesses (Internal — where we fall short)

| # | Weakness | Impact (H/M/L) | Fix? | Cost to Fix |
|---|----------|-----------------|------|-------------|
| 1 | | | Yes/No/Later | |
| 2 | | | | |
| 3 | | | | |
| 4 | | | | |
| 5 | | | | |

**Key question:** If a competitor attacked us, where would they hit?

---

## Opportunities (External — what we could exploit)

| # | Opportunity | Timeframe | Effort | Potential Impact |
|---|------------|-----------|--------|-----------------|
| 1 | | Now/Soon/Later | Low/Med/High | Low/Med/High |
| 2 | | | | |
| 3 | | | | |
| 4 | | | | |
| 5 | | | | |

**Key question:** What's changing in the market that benefits us?

---

## Threats (External — what could hurt us)

| # | Threat | Likelihood (H/M/L) | Impact (H/M/L) | Mitigation |
|---|--------|---------------------|-----------------|------------|
| 1 | | | | |
| 2 | | | | |
| 3 | | | | |
| 4 | | | | |
| 5 | | | | |

**Key question:** What keeps us up at night?

---

## Strategic Actions (Combine quadrants)

### SO Strategies (Strengths + Opportunities)
Use strengths to capture opportunities:
1.
2.

### WO Strategies (Weaknesses + Opportunities)
Fix weaknesses to unlock opportunities:
1.
2.

### ST Strategies (Strengths + Threats)
Use strengths to defend against threats:
1.
2.

### WT Strategies (Weaknesses + Threats)
Weaknesses that make threats worse — fix these first:
1.
2.

---

## Priority Matrix

| Action | Urgency | Impact | Do When |
|--------|---------|--------|---------|
| | High/Low | High/Low | Now / This month / This quarter / Backlog |
| | | | |
| | | | |
| | | | |

**Rule of thumb:**
- High urgency + High impact → Do now
- Low urgency + High impact → Schedule this month
- High urgency + Low impact → Delegate or batch
- Low urgency + Low impact → Backlog or skip

---
Generated by Market Research Pro — SWOT Generator
TEMPLATE

echo "✅ SWOT analysis created: $OUTPUT"
echo "Be honest — especially about weaknesses and threats. The value is in the truth."
