#!/usr/bin/env bash
# ICP (Ideal Customer Profile) Builder
# Generates a structured ICP document from guided inputs
# Usage: ./icp-builder.sh <output-file>

set -uo pipefail

OUTPUT="${1:-workspace/artifacts/icp-profile.md}"
mkdir -p "$(dirname "$OUTPUT")"

cat > "$OUTPUT" << 'TEMPLATE'
# Ideal Customer Profile (ICP)

## Target Customer
- **Industry:**
- **Company size:** (employees / revenue range)
- **Geography:** (city / region / country)
- **Decision maker role:** (title, department)
- **Budget range:**

## Pain Points (rank 1-5 by severity)
| # | Pain Point | Severity | Current Workaround |
|---|-----------|----------|-------------------|
| 1 | | /5 | |
| 2 | | /5 | |
| 3 | | /5 | |

## Buying Triggers (signals they need help NOW)
- [ ] Recently hired for [role] → indicates [gap]
- [ ] Raised funding → has budget, needs to scale
- [ ] Negative reviews mentioning [specific issue]
- [ ] Job posting for [role you could replace/augment]
- [ ] Website shows [outdated/missing feature]
- [ ] Competitor just [launched/pivoted] → pressure to respond

## Where to Find Them
| Source | Search Query | Expected Volume |
|--------|-------------|-----------------|
| LinkedIn Sales Nav | | |
| Google Maps | | |
| Industry directory | | |
| Job boards | | |
| Reddit/Twitter | | |

## Disqualifiers (do NOT contact if)
- Company size too small/large: < ___ or > ___ employees
- Already using competitor: ___
- Industry mismatch: ___
- No budget signals: ___

## One-Sentence Pain Statement
> "[Target customer] struggles with [specific pain] because [root cause], which costs them [measurable impact]."

## Personalization Hooks (per prospect)
| Prospect | Company | Hook | Source |
|----------|---------|------|--------|
| | | | |
| | | | |
| | | | |

---
Generated by Cold Outreach Pro — ICP Builder
TEMPLATE

echo "✅ ICP template created: $OUTPUT"
echo "Fill in the blanks, then use this to drive your outreach campaigns."
