#!/usr/bin/env bash
# Cold Outreach Sequence Generator
# Creates a multi-touch outreach sequence from ICP data
# Usage: ./sequence-generator.sh <prospect-name> <industry> <pain-point> [output-file]

set -uo pipefail

PROSPECT="${1:?Usage: sequence-generator.sh <prospect-name> <industry> <pain-point> [output-file]}"
INDUSTRY="${2:?Missing industry}"
PAIN="${3:?Missing pain point}"
OUTPUT="${4:-workspace/artifacts/sequence-${PROSPECT// /-}.md}"
mkdir -p "$(dirname "$OUTPUT")"

cat > "$OUTPUT" << TEMPLATE
# Outreach Sequence: $PROSPECT
**Industry:** $INDUSTRY
**Core Pain:** $PAIN
**Created:** $(date +%Y-%m-%d)

---

## Touch 1 — Cold Email (Day 0)
**Subject line options (A/B test):**
- A: "$PAIN — quick question"
- B: "How [similar company] solved $PAIN"
- C: "[First name], noticed [observation]"

**Body (PAS framework):**
\`\`\`
Hi [First name],

[PROBLEM — 1 sentence showing you understand their pain]
I noticed [specific observation about their company related to $PAIN].

[AGITATE — 1-2 sentences on cost of inaction]
For most $INDUSTRY companies, this means [consequence]. [Data point if available].

[SOLVE — 1 sentence, soft CTA]
We helped [similar company/role] [specific result]. Worth a 15-min call to see if we can do the same?

[Your name]
\`\`\`

**Checklist:**
- [ ] Personalized observation (LinkedIn, website, recent news)
- [ ] Under 125 words
- [ ] One clear CTA
- [ ] No attachments (kills deliverability)
- [ ] Sent Tue-Thu, 8-10 AM their timezone

---

## Touch 2 — Follow-up Email (Day 3)
**Subject:** Re: [Touch 1 subject]

\`\`\`
Hi [First name],

Quick follow-up on my note about $PAIN.

[Add ONE new piece of value — stat, case study, insight]

Would [specific day] or [specific day] work for a quick call?

[Your name]
\`\`\`

**Rule:** Same thread (reply to Touch 1). No "just checking in."

---

## Touch 3 — LinkedIn Connection (Day 5)
**Connection note (under 300 chars):**
\`\`\`
Hi [First name] — I work with $INDUSTRY companies on [related topic]. Sent you a note about $PAIN. Would love to connect and share what's working for others in the space.
\`\`\`

**If already connected, send DM:**
\`\`\`
Hey [First name], I shared some thoughts via email on $PAIN. 
Quick question — is that something you're actively trying to solve, or is it on the back burner?
\`\`\`

---

## Touch 4 — Value Bomb Email (Day 8)
**Subject:** "[Relevant resource] for $INDUSTRY"

\`\`\`
Hi [First name],

No pitch today — just something I thought you'd find useful.

[Link to genuinely valuable resource: article, tool, report, benchmark data relevant to $PAIN and $INDUSTRY]

We put this together based on [X customers/data points]. Happy to walk through the highlights if useful.

[Your name]
\`\`\`

**Rule:** This must be actual value. Not a disguised pitch.

---

## Touch 5 — Breakup Email (Day 14)
**Subject:** "Should I close your file?"

\`\`\`
Hi [First name],

I've reached out a few times about $PAIN. I'll assume the timing isn't right.

If things change, I'm here. Just reply to this thread.

Either way — good luck with [something specific to their business].

[Your name]

P.S. [One-liner about recent result: "We just helped [company] achieve [result] — happy to share how if you're ever curious."]
\`\`\`

**Why this works:** Loss aversion. "Close your file" triggers FOMO. Gets 2-3x reply rate of normal follow-ups.

---

## Sequence Tracking

| Touch | Channel | Day | Sent | Opened | Replied | Next Action |
|-------|---------|-----|------|--------|---------|-------------|
| 1 | Email | 0 | [ ] | [ ] | [ ] | |
| 2 | Email | 3 | [ ] | [ ] | [ ] | |
| 3 | LinkedIn | 5 | [ ] | — | [ ] | |
| 4 | Email | 8 | [ ] | [ ] | [ ] | |
| 5 | Email | 14 | [ ] | [ ] | [ ] | |

## If They Reply

**Positive:** Schedule call within 24hrs. Send calendar link immediately.
**Objection:** Check references/objection-handling.md for response framework.
**"Not now":** Ask "When would be a better time?" and set reminder.
**"Not interested":** Thank them, ask for referral: "Is there someone on your team who handles [topic]?"

---
Generated by Cold Outreach Pro — Sequence Generator
TEMPLATE

echo "✅ Sequence created: $OUTPUT"
echo "Personalize each touch before sending. Generic outreach = spam."
