#!/usr/bin/env bash
# Competitive Battle Card Generator
# Creates a structured competitor analysis template
# Usage: ./battle-card.sh <competitor-name> <output-file>

set -uo pipefail

COMPETITOR="${1:?Usage: battle-card.sh <competitor-name> [output-file]}"
OUTPUT="${2:-workspace/artifacts/battlecard-${COMPETITOR// /-}.md}"
mkdir -p "$(dirname "$OUTPUT")"

cat > "$OUTPUT" << TEMPLATE
# Battle Card: $COMPETITOR

## Overview
- **Company:** $COMPETITOR
- **Website:**
- **Founded:**
- **Size:** (employees / funding / revenue if public)
- **HQ:**

## Their Positioning
- **Homepage H1:** (copy their exact headline)
- **Tagline:**
- **Primary audience:**
- **Core promise:**

## Product Comparison

| Feature | Us | $COMPETITOR | Advantage |
|---------|-----|------------|-----------|
| | | | Us / Them / Tie |
| | | | |
| | | | |
| | | | |
| | | | |

## Pricing
- **Their model:** (freemium / subscription / one-time / usage)
- **Their price:** \$___/[unit]
- **Our price:** \$___/[unit]
- **Price positioning:** We are (cheaper / similar / premium)

## Their Strengths (be honest)
1.
2.
3.

## Their Weaknesses (from reviews, forums, user feedback)
1. Source:
2. Source:
3. Source:

## Where We Win
- **Scenario:** When the customer needs [X], we win because...
- **Scenario:** When the customer values [Y], we win because...
- **Scenario:** When the customer is [Z size/type], we win because...

## Where We Lose
- **Scenario:** When the customer needs [X], they win because...
- **Scenario:** When the customer already uses [Y], switching cost is...

## Objection Handling

**"Why not just use $COMPETITOR?"**
>

**"$COMPETITOR is cheaper"**
>

**"$COMPETITOR has more features"**
>

**"$COMPETITOR is more established"**
>

## Evidence Sources
| Source | URL | What We Learned | Date Checked |
|--------|-----|-----------------|--------------|
| G2 Reviews | | | |
| Reddit | | | |
| Their Blog | | | |
| Job Postings | | | |
| Crunchbase | | | |

## Key Takeaway
> One sentence: why a customer in our ICP should choose us over $COMPETITOR.

---
Generated by Market Research Pro — Battle Card Generator
TEMPLATE

echo "✅ Battle card created: $OUTPUT"
echo "Fill in with real research. Check G2, Capterra, Reddit, and their job postings."
