#!/usr/bin/env bash
# Competitor Quick Scan
# Extracts key info from a competitor's website for battle card research
# Usage: ./competitor-scraper.sh <url> [output-file]
# Requires: curl

set -uo pipefail

URL="${1:?Usage: competitor-scraper.sh <url> [output-file]}"
DOMAIN=$(echo "$URL" | sed 's|https\?://||' | sed 's|/.*||' | sed 's|www\.||')
OUTPUT="${2:-workspace/artifacts/scan-${DOMAIN}.md}"
mkdir -p "$(dirname "$OUTPUT")"

echo "🔍 Scanning $URL ..."

# Fetch the page
HTML=$(curl -sL --max-time 15 -A "Mozilla/5.0 (compatible; ResearchBot/1.0)" "$URL" 2>/dev/null || echo "")

if [ -z "$HTML" ]; then
  echo "❌ Could not fetch $URL"
  exit 1
fi

# Extract title
TITLE=$(echo "$HTML" | grep -oi '<title>[^<]*</title>' | head -1 | sed 's/<[^>]*>//g' | xargs)

# Extract meta description
META_DESC=$(echo "$HTML" | grep -oi 'meta[^>]*name="description"[^>]*content="[^"]*"' | head -1 | sed 's/.*content="//;s/".*//' | head -c 200)
[ -z "$META_DESC" ] && META_DESC=$(echo "$HTML" | grep -oi 'meta[^>]*content="[^"]*"[^>]*name="description"' | head -1 | sed 's/.*content="//;s/".*//' | head -c 200)

# Extract H1
H1=$(echo "$HTML" | grep -oi '<h1[^>]*>[^<]*</h1>' | head -1 | sed 's/<[^>]*>//g' | xargs)

# Extract OG tags
OG_TITLE=$(echo "$HTML" | grep -oi 'meta[^>]*property="og:title"[^>]*content="[^"]*"' | head -1 | sed 's/.*content="//;s/".*//')
OG_DESC=$(echo "$HTML" | grep -oi 'meta[^>]*property="og:description"[^>]*content="[^"]*"' | head -1 | sed 's/.*content="//;s/".*//')

# Check for pricing page
HAS_PRICING="No"
echo "$HTML" | grep -qi "pricing\|plans\|/pricing" && HAS_PRICING="Likely (found 'pricing' references)"

# Check for common tech
TECH_SIGNALS=""
echo "$HTML" | grep -qi "react\|next\.js\|__next" && TECH_SIGNALS="${TECH_SIGNALS}React/Next.js, "
echo "$HTML" | grep -qi "vue\|nuxt" && TECH_SIGNALS="${TECH_SIGNALS}Vue/Nuxt, "
echo "$HTML" | grep -qi "wordpress\|wp-content" && TECH_SIGNALS="${TECH_SIGNALS}WordPress, "
echo "$HTML" | grep -qi "shopify" && TECH_SIGNALS="${TECH_SIGNALS}Shopify, "
echo "$HTML" | grep -qi "webflow" && TECH_SIGNALS="${TECH_SIGNALS}Webflow, "
echo "$HTML" | grep -qi "squarespace" && TECH_SIGNALS="${TECH_SIGNALS}Squarespace, "
echo "$HTML" | grep -qi "wix" && TECH_SIGNALS="${TECH_SIGNALS}Wix, "
echo "$HTML" | grep -qi "hubspot" && TECH_SIGNALS="${TECH_SIGNALS}HubSpot, "
echo "$HTML" | grep -qi "intercom" && TECH_SIGNALS="${TECH_SIGNALS}Intercom, "
echo "$HTML" | grep -qi "segment\|analytics" && TECH_SIGNALS="${TECH_SIGNALS}Analytics, "
echo "$HTML" | grep -qi "stripe" && TECH_SIGNALS="${TECH_SIGNALS}Stripe, "
echo "$HTML" | grep -qi "google-analytics\|gtag\|gtm" && TECH_SIGNALS="${TECH_SIGNALS}Google Analytics, "
TECH_SIGNALS=$(echo "$TECH_SIGNALS" | sed 's/, $//')
[ -z "$TECH_SIGNALS" ] && TECH_SIGNALS="Not detected"

# Check HTTPS
HTTPS="No"
echo "$URL" | grep -qi "^https" && HTTPS="Yes"

# Count links
LINK_COUNT=$(echo "$HTML" | grep -oi 'href="[^"]*"' | wc -l)

# Social links
SOCIALS=""
echo "$HTML" | grep -qi "twitter.com\|x.com" && SOCIALS="${SOCIALS}Twitter/X, "
echo "$HTML" | grep -qi "linkedin.com" && SOCIALS="${SOCIALS}LinkedIn, "
echo "$HTML" | grep -qi "github.com" && SOCIALS="${SOCIALS}GitHub, "
echo "$HTML" | grep -qi "youtube.com" && SOCIALS="${SOCIALS}YouTube, "
echo "$HTML" | grep -qi "facebook.com" && SOCIALS="${SOCIALS}Facebook, "
echo "$HTML" | grep -qi "instagram.com" && SOCIALS="${SOCIALS}Instagram, "
echo "$HTML" | grep -qi "discord" && SOCIALS="${SOCIALS}Discord, "
SOCIALS=$(echo "$SOCIALS" | sed 's/, $//')
[ -z "$SOCIALS" ] && SOCIALS="None found"

cat > "$OUTPUT" << REPORT
# Competitor Scan: $DOMAIN
**URL:** $URL
**Scanned:** $(date +%Y-%m-%d\ %H:%M)

---

## Homepage Positioning
- **Page title:** $TITLE
- **H1:** ${H1:-Not found}
- **Meta description:** ${META_DESC:-Not found}
- **OG title:** ${OG_TITLE:-Not set}
- **OG description:** ${OG_DESC:-Not set}

## Technical Signals
- **HTTPS:** $HTTPS
- **Tech stack detected:** $TECH_SIGNALS
- **Links on page:** $LINK_COUNT
- **Pricing page:** $HAS_PRICING

## Social Presence
$SOCIALS

## Raw Positioning Analysis
> **Their headline promise:** ${H1:-[check manually]}
> **What they think they sell:** ${META_DESC:-[check manually]}
> **Gap analysis:** [Compare to your positioning — where are they different? Where are they weak?]

## Next Steps
- [ ] Visit pricing page: $URL/pricing
- [ ] Check G2/Capterra reviews
- [ ] Search Reddit for opinions
- [ ] Look at job postings (signals priorities)
- [ ] Generate battle card: \`bash scripts/battle-card.sh "$DOMAIN"\`

---
Generated by Market Research Pro — Competitor Scraper
REPORT

echo "✅ Scan saved: $OUTPUT"
echo "This is automated surface-level intel. Pair with manual research for depth."
