#!/usr/bin/env bash
# TAM/SAM/SOM Calculator
# Generates a structured market sizing document
# Usage: ./tam-calculator.sh <output-file>

set -uo pipefail

OUTPUT="${1:-workspace/artifacts/market-sizing.md}"
mkdir -p "$(dirname "$OUTPUT")"

cat > "$OUTPUT" << 'TEMPLATE'
# Market Sizing — TAM / SAM / SOM

## Product/Service
- **What you sell:**
- **Who you sell to:**
- **Price point:** $___/[unit]
- **Pricing model:** (one-time / subscription / usage)

## TAM (Total Addressable Market)
The entire market if you had 100% share with zero constraints.

**Top-down approach:**
- Total [customers/businesses] in [category]: ___
- × Average annual spend on [solution type]: $___
- = **TAM: $___**
- Source:

**Bottom-up approach:**
- Total potential customers you could ever serve: ___
- × Your price per [unit/year]: $___
- = **TAM: $___**
- Source:

**Cross-check:** Do both approaches land within 2x of each other? If not, revisit assumptions.

## SAM (Serviceable Addressable Market)
The portion you can actually reach with your product, geography, and go-to-market.

**Filters applied:**
- Geography: ___ (reduces TAM by ___%)
- Customer segment: ___ (reduces by ___%)
- Technical fit: ___ (reduces by ___%)
- Language/regulation: ___ (reduces by ___%)

**Calculation:**
- TAM: $___
- × Reachable %: ___%
- = **SAM: $___**

## SOM (Serviceable Obtainable Market)
What you can realistically capture in [timeframe].

**Assumptions:**
- Market share target: ___% (be honest — 1-5% for year 1 is common)
- Sales capacity: ___ [deals/customers] per [month/quarter]
- Conversion rate: ___% of pipeline
- Ramp time: ___ months to full capacity

**Calculation:**
- SAM: $___
- × Realistic capture rate: ___%
- = **SOM: $___**

## Confidence Assessment

| Layer | Estimate | Confidence | Key Assumption |
|-------|----------|------------|----------------|
| TAM | $__ | Low/Med/High | |
| SAM | $__ | Low/Med/High | |
| SOM | $__ | Low/Med/High | |

## What Would Change These Numbers?
- **Upside:** (new segment, geographic expansion, price increase)
- **Downside:** (competitor entry, regulation, market contraction)
- **Wild card:** (technology shift, platform change, macro event)

---
Generated by Market Research Pro — TAM Calculator
TEMPLATE

echo "✅ Market sizing template created: $OUTPUT"
echo "Fill in with real data. A smaller defensible number beats a huge vague one."
