#!/usr/bin/env python3
"""
Brain Metrics CLI — Phase 4C Observability

Summarizes brain query metrics from the log file generated by metrics.py.

Usage:
    python3 scripts/brain_metrics.py --today     # Today's summary
    python3 scripts/brain_metrics.py --week      # Last 7 days
    python3 scripts/brain_metrics.py --trend     # Today vs 7-day average
    python3 scripts/brain_metrics.py --date 2026-05-07  # Specific date
    python3 scripts/brain_metrics.py --rollup    # Generate daily rollup file

Output:
    Terminal summary with color coding for thresholds.
"""

import json
import sys
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional

LOG_DIR = Path("/data/.openclaw/workspace/logs")
LOG_DIR.mkdir(parents=True, exist_ok=True)

# Thresholds for color coding
THRESHOLDS = {
    "latency_ms_p95": {"good": 100, "warn": 500},
    "hit_rate": {"good": 0.70, "warn": 0.50},
    "error_rate": {"good": 0.02, "warn": 0.10},
    "fallback_rate": {"good": 0.30, "warn": 0.50},
}


def color_code(value: float, metric: str) -> str:
    """Return ANSI color code prefix for a metric value."""
    t = THRESHOLDS.get(metric, {})
    if not t:
        return ""

    # Lower is better: latency, error_rate, fallback_rate
    if metric in ["latency_ms_p95", "error_rate", "fallback_rate"]:
        if value <= t["good"]:
            return "\033[32m"  # green
        elif value <= t["warn"]:
            return "\033[33m"  # yellow
        else:
            return "\033[31m"  # red
    # Higher is better: hit_rate
    else:
        if value >= t["good"]:
            return "\033[32m"
        elif value >= t["warn"]:
            return "\033[33m"
        else:
            return "\033[31m"


def reset_color() -> str:
    return "\033[0m"


def load_raw_jsonl(date_str: str) -> List[Dict[str, Any]]:
    """Load raw metrics from .jsonl file for a specific date."""
    log_file = LOG_DIR / f"brain-metrics-{date_str}.jsonl"
    if not log_file.exists():
        return []

    entries = []
    with open(log_file) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                entries.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return entries


def load_daily_json(date_str: str) -> Optional[Dict[str, Any]]:
    """Load pre-computed daily rollup."""
    rollup_file = LOG_DIR / f"brain-metrics-daily-{date_str}.json"
    if not rollup_file.exists():
        return None
    with open(rollup_file) as f:
        return json.load(f)


def compute_daily_rollup(date_str: str) -> Dict[str, Any]:
    """
    Compute daily aggregates from raw jsonl entries.
    Returns empty dict with zero values if no data.
    """
    entries = load_raw_jsonl(date_str)

    if not entries:
        return {
            "date": date_str,
            "queries": 0,
            "hit_rate": 0.0,
            "error_rate": 0.0,
            "fallback_rate": 0.0,
            "avg_latency_ms": 0.0,
            "p95_latency_ms": 0.0,
            "brain_sourced_rate": 0.0,
            "top_intents": {},
        }

    total = len(entries)
    hits = sum(1 for e in entries if e.get("hit", False))
    errors = sum(1 for e in entries if e.get("error"))
    brain_sourced = sum(1 for e in entries if e.get("brain_sourced", False))
    latencies = [e.get("latency_ms", 0) for e in entries]

    hit_rate = hits / total if total else 0
    error_rate = errors / total if total else 0
    fallback_rate = (total - brain_sourced) / total if total else 0

    avg_latency = sum(latencies) / len(latencies) if latencies else 0
    p95_latency = sorted(latencies)[int(len(latencies) * 0.95)] if latencies else 0

    intents: Dict[str, int] = {}
    for e in entries:
        intent = e.get("intent", "unknown")
        intents[intent] = intents.get(intent, 0) + 1

    # Sort intents by count descending
    sorted_intents = dict(sorted(intents.items(), key=lambda x: x[1], reverse=True)[:10])

    return {
        "date": date_str,
        "queries": total,
        "hit_rate": round(hit_rate, 4),
        "error_rate": round(error_rate, 4),
        "fallback_rate": round(fallback_rate, 4),
        "avg_latency_ms": round(avg_latency, 2),
        "p95_latency_ms": round(p95_latency, 2),
        "brain_sourced_rate": round(brain_sourced / total, 4) if total else 0,
        "top_intents": sorted_intents,
    }


def save_daily_rollup(date_str: str, rollup: Dict[str, Any]) -> None:
    """Save daily rollup to JSON file."""
    rollup_file = LOG_DIR / f"brain-metrics-daily-{date_str}.json"
    with open(rollup_file, "w") as f:
        json.dump(rollup, f, indent=2)


def print_daily_summary(date_str: str, rollup: Dict[str, Any]) -> None:
    """Print a nice terminal summary for one day."""
    print()
    print(f"{'=' * 60}")
    print(f"  Brain Metrics — {date_str}")
    print(f"{'=' * 60}")

    if rollup["queries"] == 0:
        print("  No queries recorded today.")
        print(f"{'=' * 60}")
        return

    q = rollup["queries"]
    hr = rollup["hit_rate"]
    er = rollup["error_rate"]
    fr = rollup["fallback_rate"]
    p95 = rollup["p95_latency_ms"]
    avg = rollup["avg_latency_ms"]

    hr_color = color_code(hr, "hit_rate")
    er_color = color_code(er, "error_rate")
    p95_color = color_code(p95, "latency_ms_p95")
    fr_color = color_code(fr, "fallback_rate")
    reset = reset_color()

    print(f"  Queries:          {q:>8}")
    print(f"  Hit rate:         {hr_color}{hr*100:>7.1f}%{reset}")
    print(f"  Error rate:       {er_color}{er*100:>7.1f}%{reset}")
    print(f"  Fallback rate:    {fr_color}{fr*100:>7.1f}%{reset}")
    print(f"  Avg latency:      {avg:>7.1f}ms")
    print(f"  P95 latency:      {p95_color}{p95:>7.1f}ms{reset}")

    intents = rollup.get("top_intents", {})
    if intents:
        print(f"\n  Top intents:")
        for intent, count in list(intents.items())[:5]:
            pct = (count / q) * 100
            print(f"    {intent:<20} {count:>4} ({pct:>5.1f}%)")

    print(f"{'=' * 60}")


def print_trend(today_rollup: Dict[str, Any], week_rollups: List[Dict[str, Any]]) -> None:
    """Print today vs 7-day average comparison."""
    print()
    print(f"{'=' * 60}")
    print(f"  Brain Metrics — Trend (Today vs 7-day Avg)")
    print(f"{'=' * 60}")

    if not week_rollups:
        print("  No historical data available.")
        return

    valid = [r for r in week_rollups if r["queries"] > 0]
    if not valid:
        print("  No queries in the last 7 days.")
        return

    avg_queries = sum(r["queries"] for r in valid) / len(valid)
    avg_hit_rate = sum(r["hit_rate"] for r in valid) / len(valid)
    avg_error_rate = sum(r["error_rate"] for r in valid) / len(valid)
    avg_p95 = sum(r["p95_latency_ms"] for r in valid) / len(valid)
    avg_fallback = sum(r["fallback_rate"] for r in valid) / len(valid)

    t = today_rollup

    def diff_arrow(today_val, avg_val, metric):
        """Return colored diff indicator."""
        delta = today_val - avg_val
        if metric in ["error_rate", "fallback_rate", "latency"]:
            # Lower is better
            if delta < -0.05:
                return f"\033[32m↓ {abs(delta)*100:.0f}%{reset_color()}"
            elif delta > 0.05:
                return f"\033[31m↑ {abs(delta)*100:.0f}%{reset_color()}"
            else:
                return f"  —"
        else:
            # Higher is better
            if delta > 0.05:
                return f"\033[32m↑ {abs(delta)*100:.0f}%{reset_color()}"
            elif delta < -0.05:
                return f"\033[31m↓ {abs(delta)*100:.0f}%{reset_color()}"
            else:
                return f"  —"

    reset = reset_color()

    print(f"  Metric               Today       7d Avg    Trend")
    print(f"  {'—' * 54}")
    print(f"  Queries              {t['queries']:>8}    {avg_queries:>7.1f}")
    print(f"  Hit rate             {t['hit_rate']*100:>7.1f}%    {avg_hit_rate*100:>6.1f}%   {diff_arrow(t['hit_rate'], avg_hit_rate, 'hit')}")
    print(f"  Error rate           {t['error_rate']*100:>7.1f}%    {avg_error_rate*100:>6.1f}%   {diff_arrow(t['error_rate'], avg_error_rate, 'error')}")
    print(f"  Fallback rate        {t['fallback_rate']*100:>7.1f}%    {avg_fallback*100:>6.1f}%   {diff_arrow(t['fallback_rate'], avg_fallback, 'fallback')}")
    print(f"  P95 latency          {t['p95_latency_ms']:>7.1f}ms   {avg_p95:>6.1f}ms")

    print(f"{'=' * 60}")


def get_date_range(end_date: str, days: int) -> List[str]:
    """Get list of date strings going back N days from end_date."""
    end = datetime.strptime(end_date, "%Y-%m-%d").date()
    return [(end - timedelta(days=i)).strftime("%Y-%m-%d") for i in range(days)]


def run_cli():
    import argparse
    parser = argparse.ArgumentParser(description="Brain Metrics CLI")
    parser.add_argument("--today", action="store_true", help="Show today's summary")
    parser.add_argument("--yesterday", action="store_true", help="Show yesterday's summary")
    parser.add_argument("--week", action="store_true", help="Show last 7 days")
    parser.add_argument("--trend", action="store_true", help="Today vs 7-day average")
    parser.add_argument("--date", type=str, help="Specific date (YYYY-MM-DD)")
    parser.add_argument("--rollup", action="store_true", help="Generate daily rollup file")
    parser.add_argument("--raw", action="store_true", help="Output raw JSON instead of terminal format")
    args = parser.parse_args()

    today = datetime.now().strftime("%Y-%m-%d")

    if args.rollup:
        rollup = compute_daily_rollup(today)
        save_daily_rollup(today, rollup)
        print(f"Daily rollup saved: logs/brain-metrics-daily-{today}.json")
        return

    if args.date:
        date_str = args.date
    elif args.yesterday:
        date_str = (datetime.now() - timedelta(days=1)).strftime("%Y-%m-%d")
    else:
        date_str = today

    # Try daily rollup first, fall back to computing from raw
    rollup = load_daily_json(date_str) or compute_daily_rollup(date_str)

    if args.week:
        dates = get_date_range(date_str, 7)
        print()
        print(f"{'=' * 60}")
        print(f"  Brain Metrics — 7-Day Summary")
        print(f"{'=' * 60}")
        for d in reversed(dates):
            r = load_daily_json(d) or compute_daily_rollup(d)
            if r["queries"] > 0:
                print(f"\n  {d}:")
                print(f"    Queries: {r['queries']}, Hit: {r['hit_rate']*100:.1f}%, "
                      f"Err: {r['error_rate']*100:.1f}%, P95: {r['p95_latency_ms']:.1f}ms")
        print(f"\n{'=' * 60}")
        return

    if args.trend:
        week_dates = get_date_range(date_str, 7)
        week_rollups = [load_daily_json(d) or compute_daily_rollup(d) for d in week_dates]
        print_trend(rollup, week_rollups)
        return

    if args.raw:
        print(json.dumps(rollup, indent=2))
        return

    print_daily_summary(date_str, rollup)


if __name__ == "__main__":
    run_cli()
