#!/usr/bin/env bash
# Keyword Research Planner
# Creates a structured keyword research template
# Usage: ./keyword-planner.sh <niche> <output-file>

set -uo pipefail

NICHE="${1:?Usage: keyword-planner.sh <niche> [output-file]}"
NICHE_SLUG=$(echo "$NICHE" | tr ' ' '-' | tr '[:upper:]' '[:lower:]')
OUTPUT="${2:-workspace/artifacts/keywords-${NICHE_SLUG}.md}"
mkdir -p "$(dirname "$OUTPUT")"

cat > "$OUTPUT" << TEMPLATE
# Keyword Research: $NICHE
**Date:** $(date +%Y-%m-%d)

## Seed Keywords
List 10-20 core terms your audience would search:

| # | Seed Keyword | Category |
|---|-------------|----------|
| 1 | | |
| 2 | | |
| 3 | | |
| 4 | | |
| 5 | | |

## Keyword Expansion

### By Intent

**Informational** (how, what, why, guide, tutorial)
| Keyword | Est. Volume | Difficulty | Content Type |
|---------|-------------|------------|-------------|
| how to [topic] | | | Blog post |
| what is [topic] | | | Guide |
| [topic] vs [alternative] | | | Comparison |
| | | | |

**Commercial** (best, top, review, comparison)
| Keyword | Est. Volume | Difficulty | Content Type |
|---------|-------------|------------|-------------|
| best [solution] for [audience] | | | Listicle |
| [product] review | | | Review |
| [product] alternatives | | | Comparison |
| | | | |

**Transactional** (buy, pricing, discount, sign up)
| Keyword | Est. Volume | Difficulty | Content Type |
|---------|-------------|------------|-------------|
| [product] pricing | | | Pricing page |
| buy [product] | | | Product page |
| [product] free trial | | | Landing page |
| | | | |

**Navigational** (brand, specific product)
| Keyword | Est. Volume | Difficulty | Content Type |
|---------|-------------|------------|-------------|
| [brand name] login | | | Login page |
| [brand name] docs | | | Docs |
| | | | |

### By Modifier

**Problem-aware:** "[pain point] solution", "fix [problem]", "stop [problem]"
**Feature-aware:** "[product] with [feature]", "[feature] tool"
**Audience-specific:** "[solution] for [role]", "[solution] for [industry]"
**Location-based:** "[solution] in [city]", "[solution] near me"
**Comparison:** "[product] vs [competitor]", "[product] or [alternative]"

## Content Map

### Pillar Pages (high-volume, broad topics)
| Pillar Topic | Target Keyword | Word Count | Priority |
|-------------|----------------|------------|----------|
| | | 2500+ | |
| | | 2500+ | |

### Cluster Pages (specific, long-tail, link to pillar)
| Cluster Topic | Target Keyword | Pillar | Word Count |
|--------------|----------------|--------|------------|
| | | | 1000-1500 |
| | | | 1000-1500 |
| | | | 1000-1500 |
| | | | 1000-1500 |

### Quick Win Opportunities
Pages/keywords where you already rank 4-20 and can push higher:
| Current Page | Keyword | Current Rank | Action |
|-------------|---------|-------------|--------|
| | | | |
| | | | |

## Competitor Keywords
Keywords your competitors rank for that you don't:
| Keyword | Competitor | Their Rank | Volume | Gap Type |
|---------|-----------|------------|--------|----------|
| | | | | Content missing |
| | | | | Need better content |
| | | | | |

## Content Calendar (Next 30 Days)

| Week | Content Piece | Target Keyword | Type | Priority |
|------|-------------|----------------|------|----------|
| 1 | | | | |
| 2 | | | | |
| 3 | | | | |
| 4 | | | | |

---
Generated by SEO Audit Pro — Keyword Planner
TEMPLATE

echo "✅ Keyword plan created: $OUTPUT"
echo "Fill in with data from Google Search Console, Ahrefs, or manual SERP analysis."
